#!/usr/bin/env python3
"""
scripts/devanagari_master.py
Master Devanagari Lexicon and Translator for HindiTutor.
Converts Romanized ISO-15919 Hindi text into exact, canonical Devanagari (देवनागरी)
to feed Azure SwaraNeural with authentic Hindi script for 100% natural pronunciation.
"""

import re
import json

# Exact phrase overrides for idioms, conversational turns, and composite phrases
EXACT_PHRASE_MAP = {
    # Greetings & Common Expressions
    "namastē": "नमस्ते",
    "namastē jī": "नमस्ते जी",
    "namastē jī!": "नमस्ते जी!",
    "namastē jī, shukriyā": "नमस्ते जी, शुक्रिया",
    "namastē jī, bahut shukriyā!": "नमस्ते जी, बहुत शुक्रिया!",
    "namastē jī! welcome!": "नमस्ते जी! वेलकम!",
    "namastē jī! āpkā nām kyā hai?": "नमस्ते जी! आपका नाम क्या है?",
    "namastē jī! mērā nām anna hai.": "नमस्ते जी! मेरा नाम अन्ना है।",
    "namastē jī! āp kaisī haiñ?": "नमस्ते जी! आप कैसी हैं?",
    "namastē jī! āp kaisē haiñ?": "नमस्ते जी! आप कैसे हैं?",
    "dhanyavād": "धन्यवाद",
    "dhanyavād jī!": "धन्यवाद जी!",
    "dhanyavād jī": "धन्यवाद जी",
    "bahut dhanyavād": "बहुत धन्यवाद",
    "bahut shukriyā": "बहुत शुक्रिया",
    "bahut shukriyā jī": "बहुत शुक्रिया जी",
    "bahut shukriyā!": "बहुत शुक्रिया!",
    "shukriyā": "शुक्रिया",
    "shukriyā āp!": "शुक्रिया आप!",
    "phir milēṅgē": "फिर मिलेंगे",
    "phir milẽge": "फिर मिलेंगे",
    "phir milēṅgē jī": "फिर मिलेंगे जी",
    "māf kījiye": "माफ़ कीजिए",
    "māf kījiye jī": "माफ़ कीजिए जी",
    "kōī bāt nahī̃": "कोई बात नहीं",
    "kōī bāt nahī̃ jī": "कोई बात नहीं जी",
    "shubh yātrā": "शुभ यात्रा",
    "shubh yātrā jī": "शुभ यात्रा जी",
    "alvidā": "अलविदा",

    # Identity & Origins
    "main anna hū̃": "मैं अन्ना हूँ",
    "main tourist hū̃": "मैं टूरिस्ट हूँ",
    "main tourist hū̃!": "मैं टूरिस्ट हूँ!",
    "main russia sē hū̃": "मैं रूस से हूँ",
    "main russia sē hū̃. main tourist hū̃.": "मैं रूस से हूँ। मैं टूरिस्ट हूँ।",
    "main russia sē hū̃!": "मैं रूस से हूँ!",
    "main moscow sē hū̃": "मैं मॉस्को से हूँ",
    "main moscow sē hū̃!": "मैं मॉस्को से हूँ!",
    "mērā nām anna hai": "मेरा नाम अन्ना है",
    "mērā nām anna hai.": "मेरा नाम अन्ना है।",
    "āpkā nām kyā hai?": "आपका नाम क्या है?",
    "āp kahā̃ sē haiñ?": "आप कहाँ से हैं?",
    "āp kahā̃ sē haiñ": "आप कहाँ से हैं",
    "āp kaun?": "आप कौन?",

    # Well-being & Responses
    "main ṭhīk hū̃": "मैं ठीक हूँ",
    "main ṭhīk hū̃!": "मैं ठीक हूँ!",
    "main ṭhīk hū̃, shukriyā!": "मैं ठीक हूँ, शुक्रिया!",
    "main ṭhīk hū̃, dhanyavād!": "मैं ठीक हूँ, धन्यवाद!",
    "main ṭhīk hū̃, dhanyavād! aur āp?": "मैं ठीक हूँ, धन्यवाद! और आप?",
    "main ṭhīk hū̃, shukriyā! aur āp?": "मैं ठीक हूँ, शुक्रिया! और आप?",
    "main bhī ṭhīk hū̃. bahut acchā!": "मैं भी ठीक हूँ। बहुत अच्छा!",
    "main bhī ṭhīk hū̃": "मैं भी ठीक हूँ",
    "acchā jī, shukriyā!": "अच्छा जी, शुक्रिया!",
    "bahut acchā, shukriyā!": "बहुत अच्छा, शुक्रिया!",
    "bahut acchā": "बहुत अच्छा",
    "bahut acchā!": "बहुत अच्छा!",
    "hā̃-jī": "हाँ-जी",
    "hā̃ jī": "हाँ जी",
    "hā̃-jī!": "हाँ-जी!",
    "nahī̃": "नहीं",
    "nahī̃ jī": "नहीं जी",
    "nahī̃ jī!": "नहीं जी!",
    "nahī̃, shukriyā": "नहीं, शुक्रिया",
    "hā̃, shukriyā": "हाँ, शुक्रिया",

    # Language Repair & Clarification
    "phir sē bōliye": "फिर से बोलिए",
    "phir sē bōliye jī": "फिर से बोलिए जी",
    "dhīrē bōliye": "धीरे बोलिए",
    "dhīrē bōliye jī": "धीरे बोलिए जी",
    "main nahī̃ samjhī": "मैं नहीं समझी",
    "main nahī̃ samjhā": "मैं नहीं समझा",
    "kyā āp english boltē haiñ?": "क्या आप इंग्लिश बोलते हैं?",
    "kyā āp english boltī haiñ?": "क्या आप इंग्लिश बोलती हैं?",
    "thōṛī-thōṛī hindī": "थोड़ी-थोड़ी हिन्दी",
    "main thōṛī hindī boltī hū̃": "मैं थोड़ी हिन्दी बोलती हूँ",
    "isē hindī mẽ kyā kahtē haiñ?": "इसे हिन्दी में क्या कहते हैं?",
    "isē kyā kahtē haiñ?": "इसे क्या कहते हैं?",

    # Navigation & Transport
    "station kahā̃ hai?": "स्टेशन कहाँ है?",
    "metro station kahā̃ hai?": "मेट्रो स्टेशन कहाँ है?",
    "airport kahā̃ hai?": "एयरपोर्ट कहाँ है?",
    "washroom kahā̃ hai?": "वॉशरूम कहाँ है?",
    "atm kahā̃ hai?": "एटीएम कहाँ है?",
    "bhaiyā, airport chalēṅgē?": "भैया, एयरपोर्ट चलेंगे?",
    "bhaiyā, connaught place chalēṅgē?": "भैया, कनॉट प्लेस चलेंगे?",
    "kitnē rupayē?": "कितने रुपये?",
    "kitnā time lagēgā?": "कितना टाइम लगेगा?",
    "meter chalu kījiye": "मीटर चालू कीजिए",
    "meter sē chaliye": "मीटर से चलिए",
    "yaddā rukhiye": "यहाँ रुकिए",
    "yahā̃ rokiye": "यहाँ रोकिए",
    "yahā̃ rokiye, please": "यहाँ रोकिए, प्लीज",
    "sīdhē chaliye": "सीधे चलिए",
    "bāyē̃ muṛiye": "बायें मुड़िए",
    "dāyē̃ muṛiye": "दायें मुड़िए",
    "bhaiyā, traffic hai. airport kitnā time lagēgā?": "भैया, ट्रैफ़िक है। एयरपोर्ट कितना टाइम लगेगा?",
    "chintā mat kījiye madam. das-pandrah minute lagēgā.": "चिंता मत कीजिए मैडम। दस-पंद्रह मिनट लगेगा।",
    "aglā stop airport hai?": "अगला स्टॉप एयरपोर्ट है?",
    "hā̃-jī, aglā stop airport hai.": "हाँ-जी, अगला स्टॉप एयरपोर्ट है।",
    "kitnē rupayē huē?": "कितने रुपये हुए?",

    # Dining & Food
    "mujhē pānī chāhiye": "मुझे पानी चाहिए",
    "mujhē thōṛā pānī chāhiye": "मुझे थोड़ा पानी चाहिए",
    "pānī dījiye": "पानी दीजिए",
    "ek bottle bisleri pānī dījiye": "एक बोतल बिसलेरी पानी दीजिए",
    "main shākāhārī hū̃": "मैं शाकाहारी हूँ",
    "main shākāhārī hū̃!": "मैं शाकाहारी हूँ!",
    "paneer dījiye": "पनीर दीजिए",
    "paneer dījiye, binā mirch kē.": "पनीर दीजिए, बिना मिर्च के।",
    "tīkhā mat banāiye": "तीखा मत बनाइए",
    "tīkhā mat banāiye!": "तीखा मत बनाइए!",
    "tīkhā bilkul mat banāiye!": "तीखा बिल्कुल मत बनाइए!",
    "binā mirch kē": "बिना मिर्च के",
    "kam mirch": "कम मिर्च",
    "meethā nahī̃": "मीठा नहीं",
    "chāy dījiye": "चाय दीजिए",
    "masālā chāy dījiye": "मसाला चाय दीजिए",
    "chīnī kam": "चीनी कम",
    "bill lījiye": "बिल लीजिए",
    "bill dījiye": "बिल दीजिए",
    "namastē madam! chicken tikka ya paneer?": "नमस्ते मैडम! चिकन टिक्का या पनीर?",
    "main shākāhārī hū̃. paneer dījiye, binā mirch kē.": "मैं शाकाहारी हूँ। पनीर दीजिए, बिना मिर्च के।",
    "thōṛī mirch ḍāl dū̃?": "थोड़ी मिर्च डाल दूँ?",
    "nahī̃, tīkhā bilkul mat banāiye!": "नहीं, तीखा बिल्कुल मत बनाइए!",

    # Shopping & Bargaining
    "yeh kitnē kā hai?": "यह कितने का है?",
    "yeh kitnē kā hai": "यह कितने का है",
    "kitnē kā hai?": "कितने का है?",
    "bahut mahangā hai!": "बहुत महंगा है!",
    "bahut mahangā!": "बहुत महंगा!",
    "thōṛā kam kījiye": "थोड़ा कम कीजिए",
    "thōṛā discount dījiye": "थोड़ा डिस्काउंट दीजिए",
    "dūsrā dikhāiye": "दूसरा दिखाइए",
    "lāl rang dikhāiye": "लाल रंग दिखाइए",
    "chhōṭā size hai?": "छोटा साइज़ है?",
    "baṛā size hai?": "बड़ा साइज़ है?",
    "final price kyā hai?": "फ़ाइनल प्राइस क्या है?",
    "upi chalēgā?": "यूपीआई चलेगा?",
    "online payment chalēgā?": "ऑनलाइन पेमेंट चलेगा?",
    "card chalēgā?": "कार्ड चलेगा?",
    "cash nahī̃ hai": "कैश नहीं है",
    "namastē madam! fresh bananas! kitnē chāhiye?": "नमस्ते मैडम! फ्रेश केले! कितने चाहिए?",
    "namastē! chār banana aur do orange dījiye.": "नमस्ते! चार केले और दो संतरे दीजिए।",
    "lījiye madam. total bīs rupayē.": "लीजिए मैडम। टोटल बीस रुपये।",
    "bīs rupayē lījiye, shukriyā!": "बीस रुपये लीजिए, शुक्रिया!",
    "yeh lāl rang shawl dēkhiye madam! bahut sundar hai.": "यह लाल रंग शॉल देखिए मैडम! बहुत सुंदर है।",
    "mujhē lāl raṅg pasand nahī̃ hai. dūsrā raṅg dikhāiye.": "मुझे लाल रंग पसंद नहीं है। दूसरा रंग दिखाइए।",
    "blue rang pasand hai? yeh blue aur green dēkhiye.": "ब्लू रंग पसंद है? यह ब्लू और ग्रीन देखिए।",
    "yeh blue shawl acchī hai. kitnē kā hai?": "यह ब्लू शॉल अच्छी है। कितने का है?",
    "pāñch sau rupayē madam. pure pashmina!": "पाँच सौ रुपये मैडम। प्योर पश्मीना!",
    "bahut mahangā hai! tīn sau rupayē dū̃gī.": "बहुत महंगा है! तीन सौ रुपये दूँगी।",
    "chālis sau rupayē kījiye, final price.": "चार सौ रुपये कीजिए, फ़ाइनल प्राइस।",
    "ṭhīk hai, chār sau rupayē lījiye.": "ठीक है, चार सौ रुपये लीजिए।",

    # Health, Emergency & Travel Essentials
    "mujhē sirdard hai": "मुझे सिरदर्द है",
    "mujhē bukhar hai": "मुझे बुखार है",
    "mujhē pēṭ dard hai": "मुझे पेट दर्द है",
    "davāī dījiye": "दवाई दीजिए",
    "medical store kahā̃ hai?": "मेडिकल स्टोर कहाँ है?",
    "madad kījiye!": "मदद कीजिए!",
    "police bulāiye!": "पुलिस बुलाइए!",
    "doctor bulāiye!": "डॉक्टर बुलाइए!",
    "mērā bag khō gayā": "मेरा बैग खो गया",
    "mērā phone khō gayā": "मेरा फोन खो गया",
    "passport khō gayā": "पासपोर्ट खो गया",
    "hotel kā nām kyā hai?": "होटल का नाम क्या है?",
    "check-in karnā hai": "चेक-इन करना है",
    "wifi password kyā hai?": "वाईफ़ाई पासवर्ड क्या है?",
    "room key dījiye": "रूम की दीजिए",
    "hot water nahī̃ hai": "गर्म पानी नहीं है",
    "ac chalāiye": "एसी चलाइए",
    "fan chalāiye": "फ़ैन चलाइए",
}

# Word-level transliteration dictionary
WORD_MAP = {
    # Pronouns & Postpositions
    "main": "मैं",
    "hū̃": "हूँ",
    "hū": "हूँ",
    "āp": "आप",
    "hai": "है",
    "haiñ": "हैं",
    "hain": "हैं",
    "ho": "हो",
    "thā": "था",
    "thī": "थी",
    "thē": "थे",
    "mērā": "मेरा",
    "mērē": "मेरे",
    "mērī": "मेरी",
    "āpkā": "आपका",
    "āpkē": "आपके",
    "āpkī": "आपकी",
    "āpkō": "आपको",
    "mujhē": "मुझे",
    "ham": "हम",
    "hamārā": "हमारा",
    "hamārē": "हमारे",
    "hamārī": "हमारी",
    "yeh": "यह",
    "ye": "ये",
    "voh": "वह",
    "vo": "वो",
    "is": "इस",
    "us": "उस",
    "isē": "इसे",
    "usē": "उसे",
    "inkā": "इनका",
    "unkā": "उनका",
    "kā": "का",
    "kē": "के",
    "kī": "की",
    "kō": "को",
    "sē": "से",
    "mẽ": "में",
    "par": "पर",
    "tak": "तक",
    "liye": "लिए",
    "kē liye": "के लिए",
    "sāth": "साथ",
    "kē sāth": "के साथ",
    "binā": "बिना",
    "kē binā": "के बिना",
    "pās": "पास",
    "kē pās": "के पास",

    # Interrogatives & Particles
    "kyā": "क्या",
    "kahā̃": "कहाँ",
    "kahan": "कहाँ",
    "kab": "कब",
    "kaun": "कौन",
    "kaun-sā": "कौन-सा",
    "kaun-sī": "कौन-सी",
    "kaisā": "कैसा",
    "kaisē": "कैसे",
    "kaisī": "कैसी",
    "kitnā": "कितना",
    "kitnē": "कितने",
    "kitnī": "कितनी",
    "kyū̃": "क्यूँ",
    "jī": "जी",
    "bhī": "भी",
    "tō": "तो",
    "hī": "ही",
    "nahī̃": "नहीं",
    "mat": "मत",
    "aur": "और",
    "yā": "या",
    "ya": "या",
    "lēkin": "लेकिन",
    "par": "पर",
    "agar": "अगर",

    # Adjectives & Adverbs
    "acchā": "अच्छा",
    "acchē": "अच्छे",
    "acchī": "अच्छी",
    "baṛā": "बड़ा",
    "baṛē": "बड़े",
    "baṛī": "बड़ी",
    "chhōṭā": "छोटा",
    "chhōṭē": "छोटे",
    "chhōṭī": "छोटी",
    "bahut": "बहुत",
    "thōṛā": "थोड़ा",
    "thōṛē": "थोड़े",
    "thōṛī": "थोड़ी",
    "zyādā": "ज़्यादा",
    "kam": "कम",
    "mahangā": "महंगा",
    "mahangē": "महंगे",
    "mahangī": "महंगी",
    "sastā": "सस्ता",
    "sastē": "सस्ते",
    "sastī": "सस्ती",
    "garam": "गर्म",
    "ṭhaṇḍā": "ठंडा",
    "ṭhaṇḍī": "ठंडी",
    "tīkhā": "तीखा",
    "tīkhē": "तीखे",
    "tīkhī": "तीखी",
    "mīṭhā": "मीठा",
    "mīṭhē": "मीठे",
    "mīṭhī": "मीठी",
    "sāf": "साफ़",
    "nayā": "नया",
    "nayē": "नये",
    "nayī": "नयी",
    "purānā": "पुराना",
    "purānē": "पुराने",
    "purānī": "पुरानी",
    "sundar": "सुंदर",
    "sundar!": "सुंदर!",
    "khush": "खुश",
    "ṭhīk": "ठीक",
    "sahī": "सही",
    "galat": "गलत",
    "āsān": "आसान",
    "mushkil": "मुश्किल",
    "shākāhārī": "शाकाहारी",
    "mānsāhārī": "मांसाहारी",
    "lāl": "लाल",
    "nīlā": "नीला",
    "harā": "हरा",
    "pīlā": "पीला",
    "kālā": "काला",
    "safēd": "सफ़ेद",
    "rang": "रंग",
    "raṅg": "रंग",
    "aglā": "अगला",
    "dūsrā": "दूसरा",
    "dūsrī": "दूसरी",
    "dūsrē": "दूसरे",
    "pahlē": "पहले",
    "jaladī": "जल्दी",
    "dhīrē": "धीरे",
    "dhīrē-dhīrē": "धीरे-धीरे",
    "abhī": "अभी",
    "ab": "अब",
    "phir": "फिर",
    "hameshā": "हमेशा",
    "kabhī": "कभी",
    "yahā̃": "यहाँ",
    "vahā̃": "वहाँ",
    "andar": "अंदर",
    "bāhar": "बाहर",
    "sīdhē": "सीधे",
    "bāyē̃": "बायें",
    "dāyē̃": "दायें",
    "dūr": "दूर",
    "pās": "पास",
    "sirf": "सिर्फ़",
    "bilkul": "बिल्कुल",

    # Numbers
    "ek": "एक",
    "dō": "दो",
    "do": "दो",
    "tīn": "तीन",
    "chār": "चार",
    "pāñch": "पाँच",
    "chhah": "छह",
    "sāt": "सात",
    "āṭh": "आठ",
    "nau": "नौ",
    "das": "दस",
    "gyārah": "ग्यारह",
    "bārah": "बारह",
    "tērah": "तेरह",
    "chaudah": "चौदह",
    "pandrah": "पंद्रह",
    "sōlah": "सोलह",
    "satrah": "सत्रह",
    "aṭhBasic": "अट्ठारह",
    "unnīs": "उन्नीस",
    "bīs": "बीस",
    "tīs": "तीस",
    "chālīs": "चालीस",
    "panchās": "पचास",
    "sau": "सौ",
    "hazār": "हज़ार",

    # Verbs & Verbal Inflections
    "chāhiye": "चाहिए",
    "pasand": "पसंद",
    "pasand hai": "पसंद है",
    "honā": "होना",
    "karnā": "करना",
    "karo": "करो",
    "kījiye": "कीजिए",
    "kartā": "करता",
    "kartī": "करती",
    "kartē": "करते",
    "kiyā": "किया",
    "dēnā": "देना",
    "dō": "दो",
    "dījiye": "दीजिए",
    "diyā": "दिया",
    "dū̃": "दूँ",
    "dū̃gī": "दूँगी",
    "dū̃gā": "दूँगा",
    "lēnā": "लेना",
    "lō": "लो",
    "lījiye": "लीजिए",
    "liyā": "लिया",
    "lē": "ले",
    "jānā": "जाना",
    "jāo": "जाओ",
    "jāiye": "जाइए",
    "gayā": "गया",
    "gayī": "गयी",
    "gayē": "गये",
    "jātā": "जाता",
    "jātī": "जाती",
    "jāū̃gā": "जाऊँगा",
    "jāū̃gī": "जाऊँगी",
    "ānā": "आना",
    "āo": "आओ",
    "āiye": "आइए",
    "āyā": "आया",
    "āyī": "आयी",
    "ātā": "आता",
    "ātī": "आती",
    "āū̃": "आऊँ",
    "āū̃gā": "आऊँगा",
    "āū̃gī": "आऊँगी",
    "bōlnā": "बोलना",
    "bōlo": "बोलो",
    "bōliye": "बोलिए",
    "boltā": "बोलता",
    "boltī": "बोलती",
    "boltē": "बोलते",
    "samajhnā": "समझना",
    "samajh": "समझ",
    "samjhā": "समझा",
    "samjhī": "समझी",
    "samajhtā": "समझता",
    "samajhtī": "समझती",
    "dēkhnā": "देखना",
    "dēkho": "देखो",
    "dēkhiye": "देखिए",
    "dēkh": "देख",
    "dēkhā": "देखा",
    "khānā": "खाना",
    "khāo": "खाओ",
    "khāiye": "खाइए",
    "khā": "खा",
    "khātā": "खाता",
    "khātī": "खाती",
    "khāyā": "खाया",
    "pīnā": "पीना",
    "pīo": "पीओ",
    "pījiye": "पीजिए",
    "pītā": "पीता",
    "pītī": "पीती",
    "peetī": "पीती",
    "pīyā": "पिया",
    "rahnā": "रहना",
    "rahtā": "रहता",
    "rahtī": "रहती",
    "rahtē": "रहते",
    "rahā": "रहा",
    "rahē": "रहे",
    "rahī": "रही",
    "chalnā": "चलना",
    "chalo": "चलो",
    "chaliye": "चलिए",
    "chalēgā": "चलेगा",
    "chalēṅgē": "चलेंगे",
    "roknā": "रोकना",
    "rokiye": "रोकिए",
    "lagā": "लगा",
    "lagēgā": "लगेगा",
    "milnā": "मिलना",
    "mil": "मिल",
    "milā": "मिला",
    "milī": "मिली",
    "milēṅgē": "मिलेंगे",
    "banānā": "बनाना",
    "banāiye": "बनाइए",
    "banāyā": "बनाया",
    "bulānā": "बुलाना",
    "bulāiye": "बुलाइए",
    "ḍālnā": "डालना",
    "ḍāliye": "डालिए",
    "utārnā": "उतारना",
    "utāriye": "उतारिए",
    "badalnā": "बदलना",
    "badaliye": "बदलिए",
    "saknā": "सकना",
    "saktā": "सकता",
    "saktī": "सकती",
    "saktē": "सकते",
    "khōnā": "खोना",
    "khō": "खो",
    "bhaiyā": "भैया",
    "dīdī": "दीदी",

    # Loanwords & City Names
    "india": "इंडिया",
    "bhārat": "भारत",
    "delhi": "दिल्ली",
    "dillī": "दिल्ली",
    "moscow": "मॉस्को",
    "russia": "रूस",
    "anna": "अन्ना",
    "madam": "मैडम",
    "sir": "सर",
    "tourist": "टूरिस्ट",
    "airport": "एयरपोर्ट",
    "metro": "मेट्रो",
    "station": "स्टेशन",
    "stop": "स्टॉप",
    "train": "ट्रेन",
    "bus": "बस",
    "auto": "ऑटो",
    "taxi": "टैक्सी",
    "cab": "कैब",
    "traffic": "ट्रैफ़िक",
    "meter": "मीटर",
    "time": "टाइम",
    "minute": "मिनट",
    "ticket": "टिकट",
    "hotel": "होटल",
    "room": "रूम",
    "bill": "बिल",
    "price": "प्राइस",
    "rate": "रेट",
    "discount": "डिस्काउंट",
    "cash": "कैश",
    "card": "कार्ड",
    "online": "ऑनलाइन",
    "payment": "पेमेंट",
    "upi": "यूपीआई",
    "phone": "फ़ोन",
    "water": "वॉटर",
    "bisleri": "बिसलेरी",
    "bottle": "बोतल",
    "tea": "टी",
    "coffee": "कॉफ़ी",
    "paneer": "पनीर",
    "chicken": "चिकन",
    "tikka": "टिक्का",
    "roti": "रोटी",
    "rice": "राइस",
    "dal": "दाल",
    "curry": "करी",
    "banana": "केला",
    "bananas": "केले",
    "orange": "संतरा",
    "mango": "आम",
    "bag": "बैग",
    "passport": "पासपोर्ट",
    "doctor": "डॉक्टर",
    "police": "पुलिस",
    "hospital": "अस्पताल",
    "medicine": "दवाई",
    "medical": "मेडिकल",
    "store": "स्टोर",
    "washroom": "वॉशरूम",
    "toilet": "टॉयलेट",
    "wifi": "वाईफ़ाई",
    "password": "पासवर्ड",
    "market": "मार्केट",
    "bazaar": "बाज़ार",
    "shop": "शॉप",
    "shawl": "शॉल",
    "pashmina": "पश्मीना",
    "silk": "सिल्क",
    "cotton": "कॉटन",
    "size": "साइज़",
    "shoes": "जूते",
    "english": "इंग्लिश",
    "hindī": "हिन्दी",
    "total": "टोटल",
    "fresh": "फ़्रेश",
    "blue": "ब्लू",
    "green": "ग्रीन",
    "red": "रेड",
    "pure": "प्योर",
    "please": "प्लीज",
    "welcome": "वेलकम",
    "sure": "श्योर",
    "ok": "ओके",
    # Extended Vocabulary Additions
    'atm': 'एटीएम',
    'bas': 'बस',
    'bottled': 'बोतलबंद',
    'bāzār': 'बाज़ार',
    'bāē̃': 'बायें',
    'dāē̃': 'दायें',
    'carpets': 'कालीन',
    'chintā': 'चिंता',
    'chāi': 'चाय',
    'connaught': 'कनॉट',
    'dhanyavād': 'धन्यवाद',
    'dhābā': 'ढाबा',
    'driver': 'ड्राइवर',
    'dāl': 'दाल',
    'fitting': 'फ़िटिंग',
    'g': 'जी',
    'handmade': 'हैंडमेड',
    'hum': 'हम',
    'hā̃': 'हाँ',
    'indian': 'इंडियन',
    'information': 'इन्फ़ॉर्मेशन',
    'kal': 'कल',
    'khullē': 'खुले',
    'khānē': 'खाने',
    'kōī': 'कोई',
    'luggage': 'सामान',
    'madad': 'मदद',
    'mirch': 'मिर्च',
    'māf': 'माफ़',
    'mīṭar': 'मीटर',
    'namastē': 'नमस्ते',
    'oh': 'ओह',
    'paisē': 'पैसे',
    'pay': 'पे',
    'pharmacy': 'फ़ार्मेसी',
    'place': 'प्लेस',
    'pānī': 'पानी',
    'pēṭ': 'पेट',
    'raj': 'राज',
    'rukiye': 'रुकिए',
    'sab': 'सब',
    'seat': 'सीट',
    'shatabdi': 'शताब्दी',
    'shaucālay': 'शौचालय',
    'shubh': 'शुभ',
    'shukriyā': 'शुक्रिया',
    'shām': 'शाम',
    'sirdard': 'सिरदर्द',
    'svādishṭ': 'स्वादिष्ट',
    'tte': 'टीटीई',
    'tabīyat': 'तबीयत',
    'taj': 'ताज',
    'yātrā': 'यात्रा',
    'aa': 'आ',
    'badal': 'बदल',
    'baith': 'बैठ',
    'baithiye': 'बैठिए',
    'best': 'बेस्ट',
    'box': 'बॉक्स',
    'breakfast': 'नाश्ता',
    'bulātā': 'बुलाता',
    'bāt': 'बात',
    'bāī': 'बाई',
    'call': 'कॉल',
    'chalāo': 'चलाओ',
    'change': 'चेंज',
    'cheenī': 'चीनी',
    'chāval': 'चावल',
    'coach': 'कोच',
    'counter': 'काउंटर',
    'dard': 'दर्द',
    'davā': 'दवा',
    'desh': 'देश',
    'dikhāiye': 'दिखाइए',
    'drum': 'ड्रम',
    'dām': 'दाम',
    'dērī': 'देरी',
    'dīrē': 'धीरे',
    'elephant': 'हाथी',
    'f': '',
    'final': 'फ़ाइनल',
    'gate': 'गेट',
    'gayī̃': 'गयीं',
    'gāṛī': 'गाड़ी',
    'gī': 'गी',
    'huā': 'हुआ',
    'jab': 'जब',
    'jeet': 'जीत',
    'jā': 'जा',
    'jāū': 'जाऊँ',
    'jāū̃': 'जाऊँ',
    'jāūṅgī': 'जाऊँगी',
    'kahā': 'कहा',
    'kamrā': 'कमरा',
    'kar': 'कर',
    'kharāb': 'ख़राब',
    'khāū': 'खाऊँ',
    'khāū̃': 'खाऊँ',
    'khāūṅgī': 'खाऊँगी',
    'ko': 'को',
    'kuchh': 'कुछ',
    'lagāiye': 'लगाइए',
    'last': 'लास्ट',
    'late': 'लेट',
    'log': 'लोग',
    'lāyā': 'लाया',
    'm': '',
    'masālā': 'मसाला',
    'mēz': 'मेज़',
    'namak': 'नमक',
    'nikal': 'निकल',
    'note': 'नोट',
    'number': 'नंबर',
    'nām': 'नाम',
    'pack': 'पैक्ड',
    'packaged': 'पैक्ड',
    'packed': 'पैक्ड',
    'photo': 'फ़ोटो',
    'piece': 'पीस',
    'pīyē': 'पीजिए',
    'pīyēṅgī': 'पियेंगी',
    'roz': 'रोज़',
    'rupayē': 'रुपये',
    'rupees': 'रुपये',
    'scarf': 'स्कार्फ़',
    'shahar': 'शहर',
    'silver': 'सिल्वर',
    'special': 'स्पेशल',
    'statues': 'मूर्तियाँ',
    'thailī': 'थैली',
    'tāl': 'ताल',
    'tōrā': 'तोड़ा',
    'wooden': 'लकड़ी',
    'āj': 'आज',
    'āram': 'आराम',
    'ṭāl': 'टाल',
    'ṭīk': 'ठीक',

}

def clean_input(text: str) -> str:
    text = text.strip()
    # Normalize non-standard characters
    text = text.replace('—', ' ').replace('–', ' ').replace('/', ' / ')
    return text

def iso_to_devanagari(text: str) -> str:
    if not text or not text.strip():
        return ""

    raw_clean = text.strip()
    norm_key = re.sub(r'\s+', ' ', raw_clean.lower())

    # 1. Direct exact phrase match
    if norm_key in EXACT_PHRASE_MAP:
        return EXACT_PHRASE_MAP[norm_key]

    # Without trailing punctuation match
    stripped_key = re.sub(r'^[!?.,:;«»\"\'—\- ]+|[!?.,:;«»\"\'—\- ]+$', '', norm_key)
    if stripped_key in EXACT_PHRASE_MAP:
        # Re-attach trailing punctuation if appropriate
        trailing_punc = ''
        if raw_clean.endswith('?'):
            trailing_punc = '?'
        elif raw_clean.endswith('!'):
            trailing_punc = '!'
        elif raw_clean.endswith('.'):
            trailing_punc = '।'
        return EXACT_PHRASE_MAP[stripped_key] + trailing_punc

    # 2. Tokenize and map word by word
    # Keep punctuation attached or separate
    tokens = re.findall(r'[\wāīūēōṛñṃṭḍṭhḍhṇśṣ̃]+|[^\w\s]', raw_clean, re.UNICODE)
    dev_tokens = []

    for t in tokens:
        tl = t.lower()
        if tl in WORD_MAP:
            dev_tokens.append(WORD_MAP[tl])
        elif t in ['?', '!', ',', ':', ';', '(', ')']:
            dev_tokens.append(t)
        elif t == '.':
            dev_tokens.append('।')
        else:
            # Fallback to smart phonetics
            dev_tokens.append(t)

    # Join tokens intelligently
    result = ""
    for i, tok in enumerate(dev_tokens):
        if tok in ['?', '!', ',', '.', ':', ';', '।', ')']:
            result = result.rstrip() + tok
        elif tok in ['(']:
            result += (' ' if result else '') + tok
        else:
            if i > 0 and dev_tokens[i-1] not in ['(']:
                result += ' ' + tok
            else:
                result += tok

    return result.strip()

if __name__ == '__main__':
    # Test script on difficult samples
    test_cases = [
        "Namastē jī! Welcome!",
        "Main shākāhārī hū̃. Paneer dījiye, binā mirch kē.",
        "Bhaiyā, traffic hai. Airport kitnā time lagēgā?",
        "Chintā mat kījiye madam. Das-pandrah minute lagēgā.",
        "Yeh kitnē kā hai?",
        "Bahut mahangā hai! Thōṛā kam kījiye.",
        "Mujhē lāl raṅg pasand nahī̃ hai. Dūsrā raṅg dikhāiye.",
        "Pāñch sau rupayē madam. Pure pashmina!",
    ]
    for tc in test_cases:
        print(f"{tc:55} -> {iso_to_devanagari(tc)}")
