#!/usr/bin/env python3
"""
export_web_bundle.py - Consolidates all 40 days and references into a web-optimized payload.
Generates dist/hindi_course_bundle.json and dist/courseBundle.ts for immediate frontend consumption.
"""

import json
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
CONTENT_DIR = BASE_DIR / "content"
DAYS_DIR = CONTENT_DIR / "days"
DIST_DIR = BASE_DIR / "dist"

def main():
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    manifest_path = CONTENT_DIR / "course_manifest.json"
    phonetics_path = CONTENT_DIR / "phonetics_guide.json"
    cognates_path = CONTENT_DIR / "cognates_index.json"

    if not manifest_path.exists():
        print(f"Error: {manifest_path} not found.")
        sys.exit(1)

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    phonetics = {}
    if phonetics_path.exists():
        with open(phonetics_path, "r", encoding="utf-8") as f:
            phonetics = json.load(f)

    cognates = {}
    if cognates_path.exists():
        with open(cognates_path, "r", encoding="utf-8") as f:
            cognates = json.load(f)

    days_data = []
    total_vocab = 0
    total_exercises = 0

    for day in range(1, 41):
        day_file = DAYS_DIR / f"day_{day:02d}.json"
        if not day_file.exists():
            print(f"Warning: {day_file} missing during bundling.")
            continue
        with open(day_file, "r", encoding="utf-8") as f:
            d = json.load(f)
            days_data.append(d)
            total_vocab += len(d.get("vocabulary", []))
            total_exercises += len(d.get("exercises", []))

    bundle = {
        "manifest": manifest,
        "phoneticsGuide": phonetics,
        "cognatesIndex": cognates,
        "days": days_data,
        "statistics": {
            "totalDays": len(days_data),
            "totalVocabulary": total_vocab,
            "totalExercises": total_exercises
        }
    }

    # Output JSON bundle
    json_out = DIST_DIR / "hindi_course_bundle.json"
    with open(json_out, "w", encoding="utf-8") as f:
        json.dump(bundle, f, ensure_ascii=False, indent=2)
    print(f"✓ JSON bundle generated: {json_out} ({len(days_data)} days bundled)")

    # Output TypeScript module
    ts_out = DIST_DIR / "courseBundle.ts"
    with open(ts_out, "w", encoding="utf-8") as f:
        f.write("/**\n * Autogenerated bundle file for Spoken Hindi for Russian Speakers\n */\n")
        f.write("export const HINDI_COURSE_BUNDLE = ")
        json.dump(bundle, f, ensure_ascii=False, indent=2)
        f.write(" as const;\n\nexport default HINDI_COURSE_BUNDLE;\n")
    print(f"✓ TypeScript module generated: {ts_out}")

if __name__ == "__main__":
    main()
